#eureka:
#  client:
#    service-url:
#      defaultZone: https://eurekaAdmin:eurekaAdmin123@testserver.sdrc.co.in:8443/eureka

#zuul:
#  routes:
#    collection-service:
#      url: https://testserver.sdrc.co.in:8443/
#    dashboard-service:
#      url: https://testserver.sdrc.co.in:8443/
      
      
      
 zuul:
  servletPath: /zuul
  host:
    connect-timeout-millis: 30000
    socket-timeout-millis: 60000
  prefix: /service
  routes:
    collection-service:
      path: /si-rmncha-collection/**
      serviceId: collection-service
      stripPrefix: false
      url: https://uat.sdrc.co.in/
    dashboard-service:
      path: /si-rmncha-dashboard/**
      serviceId: dashboard-service
      stripPrefix: false
      url: https://uat.sdrc.co.in/