#eureka:
#  client:
#    service-url:
#      defaultZone: https://eurekaAdmin:eurekaAdmin123@testserver.sdrc.co.in:8443/eureka

#zuul:
#  routes:
#    collection-service:
#      url: https://testserver.sdrc.co.in:8443/
#    dashboard-service:
#      url: https://testserver.sdrc.co.in:8443/
      
      
      
 zuul:
  routes:
    collection-service:
      url: https://testserver.sdrc.co.in:8443/
    dashboard-service:
      url: https://testserver.sdrc.co.in:8443/